<a href="https://colab.research.google.com/github/vijay-psg587/gen_ai_llama2/blob/main/test_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Testing the `PIPELINE` of transfomers




In [ ]:
!pip install transformers accelerate huggingface_hub pydantic python_dotenv icecream torch

## Pre-trained model - tokenizing, processing and post processing



In [2]:
!huggingface-cli  logout

Not logged in!


## Login to Huggingface


## Load the necessary Keys

In [ ]:
import os
#os.environ["HF_API_KEY"]="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" # this is set a secret in colab
os.environ["HF_MODEL"]= "mistralai/Mixtral-8x7B-Instruct-v0.1"

## decoder test models
os.environ["HF_DECODER_BERT_UNCASED"]="bert-base-uncased"
os.environ["HF_DECODER_DISTILL_BERT_CHECKPOINT"] = "distilbert-base-uncased-finetuned-sst-2-english"
os.environ["HF_DECODER_DISTILL_BERT_FINE_TUNED"] = "distilbert-base-uncased-finetuned-sst-2-english"

print(os.getenv("HF_API_KEY"))

In [8]:
# To access colab secrets
from google.colab import userdata
print(userdata.get('HF_TOKEN'))

import os
from icecream import ic
try:
  import huggingface_hub as hfb
  hfb.login(userdata.get('HF_TOKEN'), add_to_git_credential=True)
except ValueError as ve:
  print("Value error:{}".format(str(ve)))
except Exception as e:
  print(f"Common error:{str(e)}")

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
Token is valid (permission: fineGrained).
Your token has been saved in your configured git credential helpers (store).
Your token has been saved to /root/.cache/huggingface/token
Login successful


## Importing the tokenizer from Transfomer

In [21]:
from transformers import AutoTokenizer, AutoConfig, AutoModel
# from transformers import TFAutoModel, PtAutoModel # these are exclusive for the respective model type to be loaded. use AutoModel which determines the model type of its own
import os
##Fetching the config


def load_model(model_name:str|None) -> tuple[any, any]:

  if model_name is None or len(model_name)  == 0:
    model_name = os.getenv("HF_DECODER_BERT_UNCASED")

  config =  AutoConfig.from_pretrained(model_name);
  print(config);
  print(os.getcwd())
  # config.save_pretrained(os.path.join(os.getcwd(),"LLM/config/BERT_UNCASED"))
  config.save_pretrained("./LLM/config/BERT_UNCASED") # this is to store in colab location

  ## Create the tokenizer -  converting the input sequence to high dimenspace vectors
  tokenizers = AutoTokenizer.from_pretrained(model_name)
  tokenizers.save_pretrained("./LLM/tokenizer/DISTILBERT")

  ## We also create the model from it
  model = AutoModel.from_pretrained(model_name)
  model.save_pretrained("./LLM/model/DISTILBERT")
  return (config, tokenizers)

load_model(model_name=os.getenv("HF_DECODER_BERT_UNCASED"))


BertConfig {
  "_name_or_path": "bert-base-uncased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.40.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

/content


(BertConfig {
   "_name_or_path": "bert-base-uncased",
   "architectures": [
     "BertForMaskedLM"
   ],
   "attention_probs_dropout_prob": 0.1,
   "classifier_dropout": null,
   "gradient_checkpointing": false,
   "hidden_act": "gelu",
   "hidden_dropout_prob": 0.1,
   "hidden_size": 768,
   "initializer_range": 0.02,
   "intermediate_size": 3072,
   "layer_norm_eps": 1e-12,
   "max_position_embeddings": 512,
   "model_type": "bert",
   "num_attention_heads": 12,
   "num_hidden_layers": 12,
   "pad_token_id": 0,
   "position_embedding_type": "absolute",
   "transformers_version": "4.40.2",
   "type_vocab_size": 2,
   "use_cache": true,
   "vocab_size": 30522
 },
 BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_t

## THis is a sample  for testing


In [10]:
from transformers import TFAutoModel
import os

model = TFAutoModel.from_pretrained(os.getenv("HF_DECODER_DISTILL_BERT_CHECKPOINT"))

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['classifier.bias', 'classifier.weight', 'pre_classifier.weight', 'pre_classifier.bias']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


## Test Sentiment Analysis with Decode Model - DISTILBERT

In [15]:
# example with return type as "tf" -tensorflow type
user_query = [
    "Wow this is awesome. I love to read this book"
    "The crimes created by the murky and foggy posts really trigger me"
]

tf_inputs = tokenizers(user_query, padding=True, truncation=True, return_tensors="tf") # u can have a return value either as "pt" or "tf"
print(tf_inputs)


# Example with return type as "pt" pytorch
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]
pt_inputs = tokenizers(raw_inputs, padding=True, truncation=True, return_tensors="pt")
print(pt_inputs)

{'input_ids': <tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[  101, 10166,  2023,  2003, 12476,  1012,  1045,  2293,  2000,
         3191,  2023,  2338, 10760,  6997,  2580,  2011,  1996, 14163,
        15952,  1998,  9666,  6292,  8466,  2428,  9495,  2033,   102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1]], dtype=int32)>}
{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [16]:
# This doesnt work , probably because the return tensors are specifically given in tf and not pt
#model = AutoModel.from_pretrained(os.getenv("HF_DECODER_DISTILL_BERT_FINE_TUNED"))

# So modified to load from TFAutoModel
model = TFAutoModel.from_pretrained(os.getenv("HF_DECODER_DISTILL_BERT_FINE_TUNED"))

outputs = model(tf_inputs)
#outputs = model(pt_inputs) # this doesnt work because the model loaded is a TF version specifically
print(outputs)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['classifier.bias', 'classifier.weight', 'pre_classifier.weight', 'pre_classifier.bias']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(1, 27, 768), dtype=float32, numpy=
array([[[ 0.5517104 ,  0.12487036,  0.3785873 , ...,  0.23843366,
          1.016581  , -0.59104943],
        [ 1.0428075 ,  0.6807785 ,  0.17305979, ...,  0.31842172,
          1.1339669 , -0.45828193],
        [ 0.93357354,  0.40049824,  0.27801323, ...,  0.20877199,
          0.99516726, -0.3051931 ],
        ...,
        [ 0.7711765 ,  0.21543685,  0.24949251, ...,  0.17886403,
          0.6729547 , -0.47490284],
        [ 0.63072234,  0.19787847,  0.26493877, ...,  0.2734502 ,
          0.98380053, -0.43003806],
        [ 1.1915655 ,  0.40287334,  0.20719248, ...,  0.3515852 ,
          0.47930717, -0.82283175]]], dtype=float32)>, hidden_states=None, attentions=None)


## Loading only the specific head -  this reduces the number of logits

In [ ]:
from transformers import TFAutoModelForSequenceClassification


model = TFAutoModelForSequenceClassification.from_pretrained(os.getenv("HF_DECODER_DISTILL_BERT_FINE_TUNED"))
outputs = model(inputs)
print(outputs.logits.shape)

## Postprocessing the output

In [ ]:
print(outputs.logits)

In [34]:
import tensorflow as tf

predictions = tf.math.softmax(outputs.logits, axis=-1)
print(predictions)

# to get the labels of each position
print(model.config.id2label)

tf.Tensor([[7.3050027e-04 9.9926955e-01]], shape=(1, 2), dtype=float32)
{0: 'NEGATIVE', 1: 'POSITIVE'}
